main:
  - name: 탐색
    url: /items
    weight: -110
  - name: 검색
    url: https://catalog.ccwps.org
    weight: -100
  - name: 생산장소
    url: /venues
    weight: -90
  - name: 생산기관
    url: /sources
    weight: -80
  - name: 촬영자
    url: /creators
    weight: -70
  - name: 주제
    url: /subjects
    weight: -60                    