# themeNoPipe: true
title: 냉전아시아 영상아카이브
description: 동아시아 및 한국의 전쟁･냉전, 평화, 일제의 식민지배 피해 및 일본군 ‘위안부’ 문제 관련 자료 조사와 연구, 교육 등의 활동을 통해 학문 발전에 이바지하는 것을 설립 목적으로 하며, (탈)냉전 평화 연구의 거점 싱크탱크, 아시아 최고 수준의 냉전 평화 아카이브, (탈)냉전 평화 교육, 정책 개발, 교류 협력의 허브를 구축하는 비전을 갖고 있다.
images:
  - img/site-feature-image.png
logo: images/logo-main.png

license:
  title_of_work: 냉전평화연구센터
  link_to_work: https://ccwps.org
  createor_of_work: 팀두루미
  link_to_creator_profile: https://durumi.io
  year_of_creation: 2022
  
footer:
  logo: img/durumi.png
  대표전화: 02-0000-0000
  팩스: 02-0000-0000
  주소: Somewhere in Seoul
  이메일: team@durumi.io
  url: http://github.com/team-durumi
  caption: Github
  github: http://github.com/team-durumi
  fb: 
  tw: 
  instagram: 
  linkedin:

cfImagePrefix: 'https://durumi.io/cdn-cgi/image'
cfImageStyles:
  thumb: 'fit=scale-down,width=300'
  full: 'fit=scale-down,width=1920'
